function summaryTable = runAllDcsOdsSpotBeamCases(options)
%runAllDcsOdsSpotBeamCases Run and summarize all 12 public cases.

arguments
    options.ProjectFolder (1,1) string = string(fileparts( ...
        mfilename("fullpath")))
    options.ResumeCompleted (1,1) logical = true
    options.DurationSeconds (1,1) double {mustBePositive} = 7200
    options.TimeStepSec (1,1) double {mustBePositive} = 2
    options.MonteCarloRuns (1,1) double {mustBeInteger,mustBePositive} = 4
    options.ZaRadiusKm double {mustBeFinite,mustBeNonnegative} = 30
    options.WriteDetailedTimeSeries (1,1) logical = true
end

projectFolder = options.ProjectFolder;
workbookFile = fullfile(projectFolder, "data", "DCS_Receivers.xlsx");
originalPath = path;
pathCleanup = onCleanup(@() path(originalPath));
addpath(projectFolder, fullfile(projectFolder, "config"), ...
    fullfile(projectFolder, "src"));
sites = loadDcsReceiverSites(workbookFile);
assert(height(sites) == 12, "ODS:AllRunCatalogCount", ...
    "The public all-case runner requires exactly 12 catalog rows.");
assert(isscalar(options.ZaRadiusKm) || ...
    numel(options.ZaRadiusKm) == height(sites),"ODS:AllRunZaCount", ...
    "ZaRadiusKm must be one scalar or one value per catalog row (%d values).", ...
    height(sites));
if isscalar(options.ZaRadiusKm)
    zaRadiiKm = repmat(options.ZaRadiusKm,height(sites),1);
else
    zaRadiiKm = options.ZaRadiusKm(:);
end

summaryParts = cell(height(sites), 1);
if all(zaRadiiKm == 30)
    summaryName = "dcs_ods_spot_beam_all_12_results.csv";
elseif all(zaRadiiKm == zaRadiiKm(1))
    zaToken = replace(string(sprintf("%.6g",zaRadiiKm(1))),".","p");
    summaryName = "dcs_ods_spot_beam_all_12_results_za" + zaToken + "km.csv";
else
    summaryName = "dcs_ods_spot_beam_all_12_results_za_custom.csv";
end
summaryFile = fullfile(projectFolder,summaryName);
for caseIndex = 1:height(sites)
    siteId = sites.SiteId(caseIndex);
    zaRadiusKm = zaRadiiKm(caseIndex);
    site = table2struct(sites(caseIndex,:));
    expectedCfg = defaultDcsOdsSpotBeamConfig(site,projectFolder, ...
        projectFolder,zaRadiusKm);
    resultFolder = expectedCfg.output.folder;
    resultFile = fullfile(resultFolder, "ods_results.mat");
    useExisting = options.ResumeCompleted && isfile(resultFile);
    if useExisting
        loaded = load(resultFile, "results");
        results = loaded.results;
        useExisting = string(results.config.meta.releaseId) == ...
            "DCS-ODS-SPOT-BEAM-SIMULATOR-PUBLIC-1.0.0" && ...
            string(results.config.site.siteId) == siteId && ...
            results.config.beams.numberPerSatellite == 10 && ...
            seconds(results.config.simulation.duration) == ...
            options.DurationSeconds && ...
            results.config.simulation.timeStepSec == options.TimeStepSec && ...
            results.config.simulation.monteCarloRuns == ...
            options.MonteCarloRuns && ...
            results.config.za.protectedCoreRadiusKm == zaRadiusKm && ...
            results.config.za.minimumActiveBeamCenterDistanceKm == zaRadiusKm;
    end

    fprintf("\n=== DCS ODS SPOT BEAM %d/%d: %s | %s | ZA %.6g km ===\n", ...
        caseIndex, height(sites), sites.Name(caseIndex), ...
        sites.Satellite(caseIndex),zaRadiusKm);
    caseTimer = tic;
    if useExisting
        fprintf("Reusing completed matching result: %s\n", resultFolder);
        resultSource = "resumed matching result";
    else
        results = runDcsOdsSpotBeamSimulator(siteId, ...
            WorkbookFile=workbookFile, OutputRoot=projectFolder, ...
            DurationSeconds=options.DurationSeconds, ...
            TimeStepSec=options.TimeStepSec, ...
            MonteCarloRuns=options.MonteCarloRuns, ...
            ZaRadiusKm=zaRadiusKm, ...
            WriteDetailedTimeSeries=options.WriteDetailedTimeSeries);
        resultSource = "new run";
    end
    elapsedSeconds = toc(caseTimer);
    assert(results.selected.feasible, "ODS:AllRunInfeasible", ...
        "No strict feasible angle pair for %s.", siteId);
    summaryParts{caseIndex} = buildSummaryRow( ...
        sites(caseIndex,:), results, resultSource, elapsedSeconds);
    completedTable = vertcat(summaryParts{1:caseIndex});
    writetable(completedTable, summaryFile);
end

summaryTable = vertcat(summaryParts{:});
fprintf("\nCompleted %d/%d cases. Summary: %s\n", ...
    height(summaryTable), height(sites), summaryFile);
clear pathCleanup
end

function row = buildSummaryRow(siteRow, results, resultSource, elapsedSeconds)
row = table(siteRow.Index, siteRow.SiteId, siteRow.Name, ...
    siteRow.Satellite, siteRow.AntennaDiameterM, siteRow.FeedHeightM, ...
    results.config.za.protectedCoreRadiusKm, ...
    results.geometry.boresightElevationDeg, ...
    results.selected.outerAngleDeg, results.selected.innerAngleDeg, ...
    results.selected.worstExceedancePercent, ...
    results.selected.maximumIOverNDb, ...
    results.selected.retaskDutyPercent, ...
    results.selected.shutdownDutyPercent, results.selected.feasible, ...
    string(resultSource), elapsedSeconds, ...
    datetime("now", TimeZone="UTC"), ...
    VariableNames=["Index","SiteId","Site","Satellite", ...
    "AntennaDiameterM","FeedHeightM","GeographicZaRadiusKm", ...
    "BoresightElevationDeg", ...
    "OuterAngleDeg","InnerAngleDeg","WorstExceedancePercent", ...
    "MaximumIOverNDb","RetaskDutyPercent","ShutdownDutyPercent", ...
    "Feasible","ResultSource","ElapsedSeconds","CompletedUtc"]);
end
