function verification = verifyDcsOdsSpotBeamSimulator(options)
%verifyDcsOdsSpotBeamSimulator Verify the public package and saved results.

arguments
    options.ProjectFolder (1,1) string = string(fileparts( ...
        mfilename("fullpath")))
    options.RequireAllResults (1,1) logical = true
end

projectFolder = options.ProjectFolder;
workbookFile = fullfile(projectFolder, "data", "DCS_Receivers.xlsx");
originalPath = path;
pathCleanup = onCleanup(@() path(originalPath));
addpath(projectFolder, fullfile(projectFolder, "config"), ...
    fullfile(projectFolder, "src"));
sites = loadDcsReceiverSites(workbookFile);
assert(height(sites) == 12, "ODS:CatalogRowCount", ...
    "The supplied catalog must contain exactly 12 cases.");

caseCount = height(sites);
verification = table(sites.Index, sites.SiteId, sites.Name, ...
    sites.Satellite, false(caseCount,1), false(caseCount,1), ...
    false(caseCount,1), false(caseCount,1), false(caseCount,1), ...
    false(caseCount,1), ...
    VariableNames=["Index","SiteId","Site","Satellite", ...
    "ConfigurationPassed","LookupPassed","ResultPresent", ...
    "ResultMetadataPassed","ResultCriterionPassed","AllPassed"]);

for caseIndex = 1:caseCount
    site = table2struct(sites(caseIndex,:));
    cfg = defaultDcsOdsSpotBeamConfig(site, projectFolder, projectFolder);
    validateOdsConfig(cfg);
    customZaCfg = defaultDcsOdsSpotBeamConfig(site,projectFolder, ...
        projectFolder,45);
    validateOdsConfig(customZaCfg);
    zaConfigurationPassed = ...
        customZaCfg.za.protectedCoreRadiusKm == 45 && ...
        customZaCfg.za.minimumActiveBeamCenterDistanceKm == 45 && ...
        customZaCfg.calibration.rampStartDistanceKm == 45 && ...
        endsWith(string(customZaCfg.output.folder),"_za45km");
    verification.ConfigurationPassed(caseIndex) = ...
        string(cfg.meta.modelName) == "DCS ODS Spot Beam Simulator" && ...
        string(cfg.meta.releaseId) == ...
        "DCS-ODS-SPOT-BEAM-SIMULATOR-PUBLIC-1.0.0" && ...
        cfg.beams.numberPerSatellite == 10 && ...
        cfg.beams.coneHalfAngleDeg == 60 && ...
        numel(cfg.resources.cochannelBeamIndices) == 3 && ...
        cfg.resources.maximumSimultaneousCochannelBeamsPerSatellite == 1 && ...
        cfg.rf.maximumBeamEirpDensityDbwPerMHz == 30 && ...
        cfg.za.protectedCoreRadiusKm == 30 && ...
        cfg.ods.outerMinimumBeamCenterDistanceKm == 180 && ...
        cfg.receiver.protectionCriterionDb == -6 && ...
        cfg.receiver.allowedExceedancePercent == 0 && ...
        cfg.site.minimumElevationDeg == 0 && ...
        zaConfigurationPassed && ...
        string(cfg.aggregation.selectionMode) == "allEligible" && ...
        string(cfg.aggregation.powerCombinationMode) == "linearSum" && ...
        cfg.antenna.farAngleGainDbiOverride == -27 && ...
        seconds(cfg.simulation.duration) == 7200 && ...
        cfg.simulation.timeStepSec == 2 && ...
        cfg.simulation.monteCarloRuns == 4;
    verification.LookupPassed(caseIndex) = verifyLookup( ...
        cfg.propagation.atmosphericLookupFile);

    resultFolder = fullfile(projectFolder, "results_" + site.SiteId);
    resultFile = fullfile(resultFolder, "ods_results.mat");
    verification.ResultPresent(caseIndex) = isfile(resultFile);
    if verification.ResultPresent(caseIndex)
        loaded = load(resultFile, "results");
        results = loaded.results;
        verification.ResultMetadataPassed(caseIndex) = ...
            string(results.config.meta.releaseId) == ...
            "DCS-ODS-SPOT-BEAM-SIMULATOR-PUBLIC-1.0.0" && ...
            string(results.config.site.siteId) == site.SiteId && ...
            results.config.beams.numberPerSatellite == 10 && ...
            results.config.antenna.diameterM == site.AntennaDiameterM && ...
            isfile(fullfile(resultFolder, "dcs_ods_angle_summary.csv")) && ...
            isfile(fullfile(resultFolder, "selected_angles.csv")) && ...
            isfile(fullfile(resultFolder, "configuration.json"));
        verification.ResultCriterionPassed(caseIndex) = ...
            results.selected.feasible && ...
            results.selected.innerAngleDeg <= results.selected.outerAngleDeg && ...
            results.selected.worstExceedancePercent == 0 && ...
            results.selected.maximumIOverNDb <= -6;
    end
end

if ~options.RequireAllResults
    verification.ResultPresent(:) = true;
    verification.ResultMetadataPassed(:) = true;
    verification.ResultCriterionPassed(:) = true;
end
verification.AllPassed = all(verification{:,5:9},2);
writetable(verification, fullfile(projectFolder, ...
    "dcs_ods_spot_beam_verification.csv"));
assert(all(verification.AllPassed), "ODS:PackageVerification", ...
    "One or more public-package checks failed.");

summaryFile = fullfile(projectFolder, ...
    "dcs_ods_spot_beam_all_12_results.csv");
if options.RequireAllResults
    assert(isfile(summaryFile), "ODS:MissingAllCaseSummary", ...
        "The all-case result summary is missing.");
    summary = readtable(summaryFile, TextType="string");
    assert(height(summary) == 12 && all(summary.Feasible) && ...
        all(summary.WorstExceedancePercent == 0) && ...
        isequal(summary.SiteId, sites.SiteId), ...
        "ODS:InvalidAllCaseSummary", ...
        "The all-case result summary is incomplete or inconsistent.");
end
fprintf("DCS_ODS_SPOT_BEAM_SIMULATOR_VERIFY_PASS %d/%d cases passed.\n", ...
    nnz(verification.AllPassed), caseCount);
clear pathCleanup
end

function passed = verifyLookup(lookupFile)
passed = isfile(lookupFile);
if ~passed
    return
end
lookup = readtable(lookupFile);
required = ["ElevationDeg","GaseousLossDb","CloudLossDb", ...
    "RainLossDb","ScintillationLossDb","TotalAtmosphericLossDb"];
passed = height(lookup) == 86 && ...
    all(ismember(required,string(lookup.Properties.VariableNames))) && ...
    lookup.ElevationDeg(1) == 5 && lookup.ElevationDeg(end) == 90 && ...
    all(diff(lookup.ElevationDeg) > 0) && ...
    all(isfinite(lookup.TotalAtmosphericLossDb)) && ...
    all(lookup.TotalAtmosphericLossDb >= 0);
end
