function summaryTable = writeDcsOdsSummary(results, selectedSite)
%writeDcsOdsSummary Write strict and practical public interpretations.

if ~isfolder(results.config.output.folder)
    mkdir(results.config.output.folder);
end
additionalMuteDepthDb = NaN;
estimatedTotalMuteDepthDb = NaN;
summaryTable = table(string(results.config.meta.modelVersion), ...
    string(selectedSite.SiteId), string(selectedSite.Name), ...
    selectedSite.LatitudeDeg, selectedSite.LongitudeDeg, ...
    string(selectedSite.Satellite), ...
    results.config.site.boresight.geoLongitudeDeg, ...
    selectedSite.AntennaDiameterM, selectedSite.FeedHeightM, ...
    results.config.site.heightM, results.config.site.minimumElevationDeg, ...
    string(results.config.site.visibilityConvention), ...
    results.config.za.minimumActiveBeamCenterDistanceKm, ...
    results.config.ods.outerMinimumBeamCenterDistanceKm, ...
    results.config.resources.carrierCount, ...
    numel(results.config.resources.cochannelBeamIndices), ...
    results.config.resources.maximumSimultaneousCochannelBeamsPerSatellite, ...
    results.config.resources.meanSatelliteCarrierDutyCycle, ...
    results.config.calibration.sidelobeCorrectionDb, ...
    results.config.rf.maximumBeamEirpDensityDbwPerMHz, ...
    results.config.beams.scanLossCompensationEnabled, ...
    results.selected.outerAngleDeg, results.selected.innerAngleDeg, ...
    results.selected.worstExceedancePercent, ...
    results.selected.robustExceedancePercent, ...
    results.selected.robustAvailabilityPercent, ...
    results.selected.practicalPercentileIOverNDb, ...
    results.selected.maximumIOverNDb, results.selected.feasible, ...
    resultInterpretation(results.selected.feasible, "strict", ...
    results.config.reporting.practicalAvailabilityPercent), ...
    results.practical.outerAngleDeg, results.practical.innerAngleDeg, ...
    results.practical.robustExceedancePercent, ...
    results.practical.robustAvailabilityPercent, ...
    results.practical.practicalPercentileIOverNDb, ...
    results.practical.maximumIOverNDb, results.practical.feasible, ...
    resultInterpretation(results.practical.feasible, "practical", ...
    results.config.reporting.practicalAvailabilityPercent), ...
    results.selected.retaskDutyPercent, ...
    results.selected.shutdownDutyPercent, ...
    additionalMuteDepthDb, estimatedTotalMuteDepthDb, ...
    VariableNames=["ModelVersion", "SiteId", "Site", "LatitudeDeg", ...
    "LongitudeDeg", "GoesAssignment", "BoresightLongitudeDeg", ...
    "AntennaDiameterM", "FeedHeightAglM", "GeodeticHeightM", ...
    "MinimumElevationDeg", "VisibilityConvention", ...
    "GeographicZaRadiusKm", "OuterRetaskDistanceKm", ...
    "CarrierCount", "CochannelBeamCount", ...
    "MaximumScheduledCochannelBeamsPerSatellite", ...
    "MeanProtectedCarrierDutyCycle", "EmpiricalSidelobeCorrectionDb", ...
    "BeamMaximumEirpDensityDbwPerMHz", "ScanLossCompensated", ...
    "OuterAngleDeg", "InnerAngleDeg", "WorstExceedancePercent", ...
    "RobustExceedancePercent", "RobustAvailabilityPercent", ...
    "PracticalPercentileIOverNDbAtStrictAngles", "MaximumIOverNDb", ...
    "Feasible", "ResultInterpretation", ...
    "PracticalOuterAngleDeg", "PracticalInnerAngleDeg", ...
    "PracticalRobustExceedancePercent", ...
    "PracticalRobustAvailabilityPercent", ...
    "PracticalPercentileIOverNDb", "PracticalMaximumIOverNDb", ...
    "PracticalFeasible", "PracticalResultInterpretation", ...
    "RetaskDutyPercent", "ShutdownDutyPercent", ...
    "AdditionalAllSkyMuteDepthNeededDb", ...
    "EstimatedTotalAllSkyMuteDepthDb"]);
writetable(summaryTable, fullfile(results.config.output.folder, ...
    "dcs_ods_angle_summary.csv"));
end

function interpretation = resultInterpretation(feasible, mode, ...
        practicalAvailabilityPercent)
if feasible && mode == "strict"
    interpretation = "Minimum searched ODS pair with zero modeled exceedance in every Monte Carlo run";
elseif feasible
    interpretation = compose("Minimum searched ODS pair meeting %.1f-percent practical availability", ...
        practicalAvailabilityPercent);
elseif mode == "strict"
    interpretation = "Least-exceeding candidate; no strict zero-exceedance pair exists in the searched grid";
else
    interpretation = compose("Least-exceeding candidate; no practical %.1f-percent-availability pair exists in the searched grid", ...
        practicalAvailabilityPercent);
end
end
